### ISSUE TITLE
How do i align the unit horizontally in this grid

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/volunteer-form#1]
<img width="601" alt="Screen Shot 2020-03-28 at 10 41 39 PM" src="https://user-images.githubusercontent.com/55412298/77838844-971a8080-7145-11ea-815a-8071927104f0.png">
 @muxlowc

**Comment by muxlowc** [comment]
@hoanganhduong 
You can remove the pad-t / pad-b that you've added to your units, and then add the class of "push" on the units - I think that should help!
